Nataliia chobu
AndrewSloth/Nova_JavaCodingTasks pull request #4
Opened 2023-05-19 17:39 UTC by nataliiachobu

Hey guys! Another test for git practice!//learning how to make approvals to merge new changes. ;))

2023-05-19 17:55 UTC, mariiasuzdal approved these changes
Great job!

2023-05-19 23:21 UTC, Nonos1500 commented
Looks good, but can you make your methods void, so it would be shorter in main method LOL, just kidding. Everything is good here

2023-05-19 23:22 UTC, Nonos1500 approved these changes

2023-05-21 06:29 UTC, AndrewSloth commented on src/nataliia_chobu/Divide.java
> +
I believe this method should be able work with all numbers. Try dividing -12 / 3 result will be 0 it is incorrect.

2023-05-21 22:05 UTC, AndrewSloth requested changes
I believe "divideWithoutDivisionOperator" method should be able work with all numbers. Try dividing -12 / 3 result will be 0 it is incorrect.

2023-05-22 03:47 UTC, AndrewSloth approved these changes

2023-05-22 03:48 UTC, merged